app = "vetra-discord-bot"
kill_timeout = 30
process_group = "app"
region = "ord"

[build]
  builder = "pakeit/boxstarter-docker"

[build.environment]
  PYTHON_VERSION = "3.11"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_dir = "/app"
  url_prefix = "/"